#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -eq 0 ]; then
    set -- php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
fi

if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
    exec "$@"
else
    exec gosu "$WWWUSER" "$@"
fi
